HOUR_MS = 60 * 60 * 1000
DAY_MS = 24 * HOUR_MS

FREE_AUTHENTICATION_PERIOD_MS = 3 * DAY_MS + 12 * HOUR_MS
PAID_AUTHENTICATION_PERIOD_MS = 10 * DAY_MS + 12 * HOUR_MS
DEFAULT_RESOURCE_RETENTION_MS = 10 * DAY_MS + 12 * HOUR_MS

S3_RESOURCE_RETENTION_DAYS = 11

ACCESS_TOKEN_ALL_LIFETIME_MS = 12 * HOUR_MS
ACCESS_TOKEN_ALL_IDLE_TIMEOUT_MS = 3 * HOUR_MS